/**
 * ============================================================
 * ASSOCIATES IN WOMENS HEALTH — SITE CONFIGURATION
 * ============================================================
 * Generated by Site Admin on April 30, 2026
 *
 * HOW TO USE:
 *   1. Save this file as config.js in your website folder
 *   2. Make sure index.html loads it: <script src="config.js"></script>
 *   3. Reload the website — your changes appear automatically
 * ============================================================
 */

const SITE_CONFIG = {
  "firmName": "Associates in Womens Health",
  "tagline": "",
  "preloaderTagline": "",
  "logoPrimary": "logos/AWH Logo-pinkwht.png",
  "logoAlternate": "logos/AWH Logo-wht.png",
  "logoHeaderChoice": "primary",
  "logoHeaderHeight": 60,
  "logoSplashChoice": "primary",
  "logoSplashHeight": 200,
  "logoSplashMode": "logo-only",
  "logoFooterChoice": "alternate",
  "logoFooterHeight": 80,
  "pageHeaders": {
    "about": {
      "label": "Meet the Team",
      "title": "the Physicians",
      "subtitle": ""
    },
    "contact": {
      "label": "Get in Touch"
    }
  },
  "attorneyName": "Dr. Matthew  Roberts, DO",
  "attorneyDegree": "DO, West Virginia School of Osteopathic Medicine, 1987",
  "attorneyCredentials": [
    "• American College of Osteopathic Obstetricians and Gynecologists, Member",
    "• American Osteopathic Association, Member",
    "• Tennessee Medical Association, Member",
    "• Women’s Health Services, President"
  ],
  "aboutBio1": "Dr. Matthew Roberts has been in practice since 1992, and on staff with Associates in Women’s Health since 1996.  He is licensed in both Tennessee and Georgia, seeing patients at both Associates in Women’s Health’s locations.",
  "aboutBio2": "He is originally from Murfreesboro, TN and presently resides in McDonald, TN with his wife, Wendy, and three children, Devin, Macey & Chase.",
  "attorneyPhoto": "staff/roberts-01.png",
  "aboutNavLabel": "Meet the Team",
  "attorneys": [
    {
      "name": "Dr. Matthew  Roberts, DO",
      "degree": "DO, West Virginia School of Osteopathic Medicine, 1987",
      "education": [
        "DO, West Virginia School of Osteopathic Medicine, 1987",
        "Middle Tennessee State University B.S. Degree, 1987"
      ],
      "photo": "staff/roberts-01.png",
      "credentials": [
        "• American College of Osteopathic Obstetricians and Gynecologists, Member",
        "• American Osteopathic Association, Member",
        "• Tennessee Medical Association, Member",
        "• Women’s Health Services, President"
      ],
      "bio1": "Dr. Matthew Roberts has been in practice since 1992, and on staff with Associates in Women’s Health since 1996.  He is licensed in both Tennessee and Georgia, seeing patients at both Associates in Women’s Health’s locations.",
      "bio2": "He is originally from Murfreesboro, TN and presently resides in McDonald, TN with his wife, Wendy, and three children, Devin, Macey & Chase.",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    },
    {
      "name": "Dr. Terry L. Williams, Jr. DO",
      "degree": "DO, West Virginia School of Osteopathic Medicine, 2004",
      "education": [
        "DO, West Virginia School of Osteopathic Medicine, 2004",
        "UT, Chattanooga Master’s Degree in Education, 1995",
        "Auburn University B.S. Degree in Education, 1992"
      ],
      "photo": "staff/williams-01.png",
      "credentials": [
        "• American College of Osteopathic Obstetricians and Gynecologists, Member",
        "• American Osteopathic Association, Member",
        "• Tennessee Medical Association, Member",
        "• Berlex Best Teaching Resident Award",
        "• W. Powell Hutcherson Award for Best Resident",
        "• APGO Excellence in Teaching Award"
      ],
      "bio1": "Dr. Williams joined Associates in Women’s Health in August 2016. He spent the previous 5 years in private practice in Ashe County, North Carolina.",
      "bio2": "Dr. Williams is an expert in the da Vinci robotic surgical system for multiple gynecological surgeries.\n\nHe is originally from the East Brainerd area, and currently resides in Ringgold, GA with his wife, Jenny and 3 children, Maggie, Ty, & Molly Beth.",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    },
    {
      "name": "Heidi Septor, MSN, FNP-C, MSCP",
      "degree": "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
      "education": [
        "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
        "UT, Chattanooga Bachelor of Science in Nursing, 2013 - Summa Cum Laude"
      ],
      "photo": "staff/septor-01.png",
      "credentials": [
        "Sigma Theta Tau International Honor Society Member",
        "SALUTE Veterans National Honor Society Member",
        "American Academy of Nurse Practitioners",
        "Daisy Award Winner"
      ],
      "bio1": "Heidi joined Associates of Women's Health in 2021. Heidi's journey began in 2002 when she enlisted in the Army and served as a combat medic, where her passion for helping others took flight. She worked as a paramedic and later a Registered Nurse.",
      "bio2": "During her deployment to Iraq, Heidi was recognized for her bravery and expertise, earning the Air Medal and the Combat Action Badge. After a fulfilling career, including serving as a Captain, she retired from the Army in 2024.\nOriginally from Massachusetts, Heidi has also called Texas and Florida home, and now has built a life in Georgia. With her wealth of experience and compassionate approach, Heidi is here to support and empower our patients every step of the way.",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    },
    {
      "name": "Hannah White, FNP",
      "degree": "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
      "education": [
        "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
        "UT, Chattanooga Bachelor of Science in Nursing, 2013 - Summa Cum Laude"
      ],
      "photo": "staff/white-01.png",
      "credentials": [
        "• Sigma Theta Tau International Honor Society",
        "• American Association of Nurse Practitioners",
        "• Chattanooga Area Nurses in Advanced Practice"
      ],
      "bio1": "",
      "bio2": "",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    }
  ],
  "phone": "(423) 910-0896",
  "phoneRaw": "14239100896",
  "fax": "",
  "email": "contact@awhealth.com",
  "address": "6845 Mountain View Rd.",
  "city": "Ooltewah",
  "state": "Tennessee",
  "stateAbbr": "TN",
  "zip": "37363",
  "locations": [
    {
      "name": "Ooltewah Office",
      "phone": "(423) 910-0896",
      "phoneRaw": "14239100896",
      "fax": "",
      "email": "contact@awhealth.com",
      "address": "6845 Mountain View Rd.",
      "city": "Ooltewah",
      "state": "Tennessee",
      "stateAbbr": "TN",
      "zip": "37363",
      "hours": [
        {
          "days": "Monday - Thursday",
          "hours": "8.30 -4.00"
        },
        {
          "days": "Friday",
          "hours": "8.30 - 12.00"
        },
        {
          "days": "Closed Weekends",
          "hours": ""
        }
      ]
    },
    {
      "name": "Ringgold Office",
      "phone": "(706) 861-4508",
      "phoneRaw": "17068614508",
      "fax": "",
      "email": "contact@awhealth.com",
      "address": "93 Robin Rd.",
      "city": "Ringgold",
      "state": "Georgia",
      "stateAbbr": "GA",
      "zip": "30736",
      "hours": []
    }
  ],
  "hours": [
    {
      "days": "Monday - Thursday",
      "hours": "8.30 -4.00"
    },
    {
      "days": "Friday",
      "hours": "8.30 - 12.00"
    },
    {
      "days": "Closed Weekends",
      "hours": ""
    }
  ],
  "socialLinks": [],
  "stats": [],
  "colors": {
    "navy": "#403749",
    "navyLight": "#403749",
    "gold": "#c358e9",
    "goldLight": "#43225d",
    "goldPale": "#faf6ec",
    "warmWhite": "#fffdf9",
    "cream": "#f9f6f0",
    "chrome": "#403749"
  },
  "fontColors": {
    "heading": "#000000",
    "body": "#000000",
    "onDark": "#ffffff",
    "onDarkMuted": "#f3f8fb"
  },
  "fontDisplay": "Merriweather",
  "fontBody": "Assistant",
  "metaDescription": "",
  "metaKeywords": "",
  "googleAnalyticsId": "",
  "formEndpoint": "",
  "pageTitles": {
    "home": "",
    "about": "",
    "contact": "",
    "privacy": ""
  },
  "heroBg": {
    "type": "video",
    "bgColor": "#0f2340",
    "imagePath": "",
    "imagePosition": "center center",
    "slides": [],
    "transition": "crossfade",
    "transitionSpeed": 2,
    "slideDuration": 8,
    "pauseOnHover": false,
    "showDots": true,
    "autoplay": true,
    "motionType": "zoom-out",
    "motionSpeed": 20,
    "overlayColor": "#0f2340",
    "overlayOpacity": 0.3,
    "videoClips": [
      {
        "mp4": "videos/hero-03.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 6
      },
      {
        "mp4": "videos/hero-00.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      },
      {
        "mp4": "videos/hero-01.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      }
    ],
    "videoFallback": "",
    "videoTransSpeed": 1.2,
    "videoHoldEnabled": false,
    "videoHold": 4
  },
  "heroHeadline": "Associates in Women's Health",
  "heroSubline": "Associates in Women’s Health is an OB/GYN practice striving to provide the highest level of quality women’s healthcare to our patients. We do this by making our patients and their health our #1 priority. Our providers have extensive education, training, and experience to provide the very best medical care for women of all ages.  We are committed to providing quality women’s healthcare with individualized treatment plans for every patient.  ",
  "heroTrustBullets": [],
  "heroPrimaryLabel": "Free Consultation",
  "heroPrimaryLinkType": "internal",
  "heroPrimaryLinkUrl": "contact",
  "heroSecondaryLabel": "Our Services",
  "heroSecondaryLinkType": "internal",
  "heroSecondaryLinkUrl": "home",
  "whyChooseUs": {
    "heading": "",
    "subtext": "",
    "badgeNum": "",
    "badgeLabel": "",
    "bullets": []
  },
  "contactHeadline": "",
  "contactSubline": "",
  "contactFormHeading": "",
  "contactFormIntro": "",
  "contactPrivacyNote": "",
  "contactForm": [
    {
      "type": "text",
      "label": "First Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "text",
      "label": "Last Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "email",
      "label": "Email Address",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "phone",
      "label": "Phone Number",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "textarea",
      "label": "Message",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    }
  ],
  "services": [],
  "faqs": [],
  "testimonials": [],
  "blogPosts": [],
  "processSteps": [],
  "processRequirements": [],
  "ctaLabel": "Contact Us",
  "pageToggles": {
    "about": true,
    "contact": true
  },
  "homeToggles": {
    "stats": true,
    "why": true,
    "testimonials": true
  },
  "customPages": [],
  "aboutSections": [
    {
      "type": "gallery",
      "label": "Office Staff",
      "background": "alt",
      "anchorId": "ringgold-office-support-staff",
      "heading": "Ringgold Office Support Staff",
      "subtitle": "",
      "galleryCols": 3,
      "items": [
        {
          "imagePath": "staff/ringgold-01.png",
          "alt": "",
          "title": "",
          "caption": ""
        },
        {
          "imagePath": "staff/ringgold-02.png",
          "alt": "",
          "title": "",
          "caption": ""
        },
        {
          "imagePath": "staff/ringgold-03.png",
          "alt": "",
          "title": "",
          "caption": ""
        }
      ]
    },
    {
      "type": "gallery",
      "label": "",
      "background": "light",
      "anchorId": "ooltewah-office-support-staff",
      "heading": "Ooltewah Office Support Staff",
      "subtitle": "",
      "galleryCols": 3,
      "items": [
        {
          "imagePath": "staff/ooltewah-01.png",
          "alt": "",
          "title": "",
          "caption": ""
        },
        {
          "imagePath": "staff/ooltewah-02.png",
          "alt": "",
          "title": "",
          "caption": ""
        },
        {
          "imagePath": "staff/ooltewah-03.png",
          "alt": "",
          "title": "",
          "caption": ""
        }
      ]
    }
  ],
  "homeSections": [],
  "footerBio": "",
  "animateStats": false,
  "contactSubmitLabel": "",
  "contactSuccessMsg": "",
  "search": {
    "placeholder": "Search...",
    "noResultsMessage": "No results for '{query}'",
    "noResultsSubtext": "Try a different search term.",
    "resultsPerPage": 5,
    "excludedPages": []
  },
  "siteAccess": "public",
  "sessionDays": 7,
  "pinPad": {
    "headline": "Members Only",
    "subtext": "Restricted Access",
    "wrongMsg": "Incorrect PIN. Try again.",
    "theme": "dark",
    "lockEmoji": "🔒",
    "backLabel": "← Back to Home",
    "maxAttempts": 3,
    "welcomeMsg": "Welcome back, {name}",
    "commissionerMsg": "Commissioner Access Granted",
    "welcomeDuration": 2,
    "showImposter": true,
    "imposterHeadline": "ACCESS DENIED",
    "imposterMsg": "This attempt has been logged.",
    "imposterDuration": 3
  },
  "members": [],
  "pageAccess": {
    "home": "public",
    "about": "public"
  },
  "_savedAt": 1777587558552
};
