/**
 * ============================================================
 * ASSOCIATES IN WOMENS HEALTH — SITE CONFIGURATION
 * ============================================================
 * Generated by Site Admin on May 2, 2026
 *
 * HOW TO USE:
 *   1. Save this file as config.js in your website folder
 *   2. Make sure index.html loads it: <script src="config.js"></script>
 *   3. Reload the website — your changes appear automatically
 * ============================================================
 */

const SITE_CONFIG = {
  "firmName": "Associates in Womens Health",
  "tagline": "",
  "preloaderTagline": "",
  "logoPrimary": "logos/AWH Logo-pinkwht.png",
  "logoAlternate": "logos/AWH Logo-wht.png",
  "logoHeaderChoice": "primary",
  "logoHeaderHeight": 60,
  "logoSplashChoice": "primary",
  "logoSplashHeight": 200,
  "logoSplashMode": "logo-only",
  "logoFooterChoice": "alternate",
  "logoFooterHeight": 80,
  "pageHeaders": {
    "about": {
      "label": "Meet the Team",
      "title": "the Physicians",
      "subtitle": ""
    },
    "contact": {
      "label": "Get in Touch"
    }
  },
  "attorneyName": "Dr. Matthew  Roberts, DO",
  "attorneyDegree": "DO, West Virginia School of Osteopathic Medicine, 1987",
  "attorneyCredentials": [
    "• American College of Osteopathic Obstetricians and Gynecologists, Member",
    "• American Osteopathic Association, Member",
    "• Tennessee Medical Association, Member",
    "• Women’s Health Services, President"
  ],
  "aboutBio1": "Dr. Matthew Roberts has been in practice since 1992, and on staff with Associates in Women’s Health since 1996.  He is licensed in both Tennessee and Georgia, seeing patients at both Associates in Women’s Health’s locations.",
  "aboutBio2": "He is originally from Murfreesboro, TN and presently resides in McDonald, TN with his wife, Wendy, and three children, Devin, Macey & Chase.",
  "attorneyPhoto": "staff/roberts-01.png",
  "aboutNavLabel": "Meet the Team",
  "attorneys": [
    {
      "name": "Dr. Matthew  Roberts, DO",
      "degree": "DO, West Virginia School of Osteopathic Medicine, 1987",
      "education": [
        "DO, West Virginia School of Osteopathic Medicine, 1987",
        "Middle Tennessee State University B.S. Degree, 1987"
      ],
      "photo": "staff/roberts-01.png",
      "credentials": [
        "• American College of Osteopathic Obstetricians and Gynecologists, Member",
        "• American Osteopathic Association, Member",
        "• Tennessee Medical Association, Member",
        "• Women’s Health Services, President"
      ],
      "bio1": "Dr. Matthew Roberts has been in practice since 1992, and on staff with Associates in Women’s Health since 1996.  He is licensed in both Tennessee and Georgia, seeing patients at both Associates in Women’s Health’s locations.",
      "bio2": "He is originally from Murfreesboro, TN and presently resides in McDonald, TN with his wife, Wendy, and three children, Devin, Macey & Chase.",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    },
    {
      "name": "Dr. Terry L. Williams, Jr. DO",
      "degree": "DO, West Virginia School of Osteopathic Medicine, 2004",
      "education": [
        "DO, West Virginia School of Osteopathic Medicine, 2004",
        "UT, Chattanooga Master’s Degree in Education, 1995",
        "Auburn University B.S. Degree in Education, 1992"
      ],
      "photo": "staff/williams-01.png",
      "credentials": [
        "• American College of Osteopathic Obstetricians and Gynecologists, Member",
        "• American Osteopathic Association, Member",
        "• Tennessee Medical Association, Member",
        "• Berlex Best Teaching Resident Award",
        "• W. Powell Hutcherson Award for Best Resident",
        "• APGO Excellence in Teaching Award"
      ],
      "bio1": "Dr. Williams joined Associates in Women’s Health in August 2016. He spent the previous 5 years in private practice in Ashe County, North Carolina.",
      "bio2": "Dr. Williams is an expert in the da Vinci robotic surgical system for multiple gynecological surgeries.\n\nHe is originally from the East Brainerd area, and currently resides in Ringgold, GA with his wife, Jenny and 3 children, Maggie, Ty, & Molly Beth.",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    },
    {
      "name": "Heidi Septor, MSN, FNP-C, MSCP",
      "degree": "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
      "education": [
        "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
        "UT, Chattanooga Bachelor of Science in Nursing, 2013 - Summa Cum Laude"
      ],
      "photo": "staff/septor-01.png",
      "credentials": [
        "Sigma Theta Tau International Honor Society Member",
        "SALUTE Veterans National Honor Society Member",
        "American Academy of Nurse Practitioners",
        "Daisy Award Winner"
      ],
      "bio1": "Heidi joined Associates of Women's Health in 2021. Heidi's journey began in 2002 when she enlisted in the Army and served as a combat medic, where her passion for helping others took flight. She worked as a paramedic and later a Registered Nurse.",
      "bio2": "During her deployment to Iraq, Heidi was recognized for her bravery and expertise, earning the Air Medal and the Combat Action Badge. After a fulfilling career, including serving as a Captain, she retired from the Army in 2024.\nOriginally from Massachusetts, Heidi has also called Texas and Florida home, and now has built a life in Georgia. With her wealth of experience and compassionate approach, Heidi is here to support and empower our patients every step of the way.",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    },
    {
      "name": "Hannah White, FNP",
      "degree": "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
      "education": [
        "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
        "UT, Chattanooga Bachelor of Science in Nursing, 2013 - Summa Cum Laude"
      ],
      "photo": "staff/white-01.png",
      "credentials": [
        "• Sigma Theta Tau International Honor Society",
        "• American Association of Nurse Practitioners",
        "• Chattanooga Area Nurses in Advanced Practice"
      ],
      "bio1": "",
      "bio2": "",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    }
  ],
  "phone": "(706) 861-4508",
  "phoneRaw": "17068614508",
  "fax": "",
  "email": "contact@awhealth.com",
  "address": "93 Robin Rd.",
  "city": "Ringgold",
  "state": "Georgia",
  "stateAbbr": "GA",
  "zip": "30736",
  "locations": [
    {
      "name": "Ringgold Office",
      "phone": "(706) 861-4508",
      "phoneRaw": "17068614508",
      "fax": "",
      "email": "contact@awhealth.com",
      "address": "93 Robin Rd.",
      "city": "Ringgold",
      "state": "Georgia",
      "stateAbbr": "GA",
      "zip": "30736",
      "hours": []
    },
    {
      "name": "Ooltewah Office",
      "phone": "(423) 910-0896",
      "phoneRaw": "14239100896",
      "fax": "",
      "email": "contact@awhealth.com",
      "address": "6845 Mountain View Rd.",
      "city": "Ooltewah",
      "state": "Tennessee",
      "stateAbbr": "TN",
      "zip": "37363",
      "hours": [
        {
          "days": "Monday - Thursday",
          "hours": "8.40 -4.00"
        },
        {
          "days": "Friday",
          "hours": "8.40 - 12.00"
        },
        {
          "days": "Closed Weekends",
          "hours": ""
        }
      ]
    },
    {
      "name": "Parkridge East Hospital",
      "phone": "(423) 698-6061",
      "phoneRaw": "14236986061",
      "fax": "",
      "email": "",
      "address": "941 Spring Creek Road",
      "city": "East Ridge",
      "state": "Tennessee",
      "stateAbbr": "TN",
      "zip": "37404",
      "hours": []
    },
    {
      "name": "PHYSICIANS Surgery Center",
      "phone": "(423) 988-1600",
      "phoneRaw": "14239881600",
      "fax": "",
      "email": "",
      "address": "924 Spring Creek Road",
      "city": "East Ridge",
      "state": "Tennessee",
      "stateAbbr": "TN",
      "zip": "37404",
      "hours": []
    }
  ],
  "hours": [],
  "socialLinks": [],
  "stats": [],
  "colors": {
    "navy": "#403749",
    "navyLight": "#403749",
    "gold": "#c358e9",
    "goldLight": "#c358e9",
    "goldPale": "#faf6ec",
    "warmWhite": "#fffdf9",
    "cream": "#f9f6f0",
    "chrome": "#403749"
  },
  "fontColors": {
    "heading": "#000000",
    "body": "#000000",
    "onDark": "#ffffff",
    "onDarkMuted": "#f3f8fb"
  },
  "fontDisplay": "Merriweather",
  "fontBody": "Assistant",
  "metaDescription": "",
  "metaKeywords": "",
  "googleAnalyticsId": "",
  "formEndpoint": "",
  "pageTitles": {
    "home": "AWH",
    "about": "AWH - Meet the Team",
    "contact": "AWH - Contact Us",
    "privacy": "AWH - Privacy"
  },
  "heroBg": {
    "type": "video",
    "bgColor": "#0f2340",
    "imagePath": "",
    "imagePosition": "center center",
    "slides": [],
    "transition": "crossfade",
    "transitionSpeed": 2,
    "slideDuration": 8,
    "pauseOnHover": false,
    "showDots": true,
    "autoplay": true,
    "motionType": "zoom-out",
    "motionSpeed": 20,
    "overlayColor": "#0f2340",
    "overlayOpacity": 0.3,
    "videoClips": [
      {
        "mp4": "videos/hero-03.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 6
      },
      {
        "mp4": "videos/hero-00.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      },
      {
        "mp4": "videos/hero-01.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      }
    ],
    "videoFallback": "",
    "videoTransSpeed": 3.9,
    "videoHoldEnabled": false,
    "videoHold": 4
  },
  "heroHeadline": "Associates in Women's Health",
  "heroSubline": "Associates in Women’s Health is an OB/GYN practice striving to provide the highest level of quality women’s healthcare to our patients. We do this by making our patients and their health our #1 priority. Our providers have extensive education, training, and experience to provide the very best medical care for women of all ages.  We are committed to providing quality women’s healthcare with individualized treatment plans for every patient.  ",
  "heroTrustBullets": [
    "2 Locations Serving GA & TN",
    "Accept All Major Heath Insurances, Medicare, & Medicaid",
    "30+ Years of Experience"
  ],
  "heroPrimaryLabel": "Contact Us",
  "heroPrimaryLinkType": "internal",
  "heroPrimaryLinkUrl": "contact",
  "heroSecondaryLabel": "Our Services",
  "heroSecondaryLinkType": "internal",
  "heroSecondaryLinkUrl": "services",
  "whyChooseUs": {
    "heading": "",
    "subtext": "",
    "badgeNum": "",
    "badgeLabel": "",
    "bullets": []
  },
  "contactHeadline": "",
  "contactSubline": "",
  "contactFormHeading": "",
  "contactFormIntro": "",
  "contactPrivacyNote": "",
  "contactForm": [
    {
      "type": "text",
      "label": "First Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "text",
      "label": "Last Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "email",
      "label": "Email Address",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "phone",
      "label": "Phone Number",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "textarea",
      "label": "Message",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    }
  ],
  "services": [],
  "faqs": [],
  "testimonials": [],
  "blogPosts": [],
  "processSteps": [],
  "processRequirements": [],
  "ctaLabel": "Contact Us",
  "pageToggles": {
    "about": true,
    "contact": true
  },
  "homeToggles": {
    "stats": true,
    "why": true,
    "testimonials": true
  },
  "customPages": [
    {
      "slug": "locations",
      "navLabel": "Locations",
      "emoji": "📄",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "text",
          "label": "Near You",
          "background": "light",
          "anchorId": "text",
          "heading": "Our Locations",
          "body": "We offer two convenient office locations, one in Ringgold GA, and the other in the Ooltewah TN. We deliver our newborns at Park Ridge East in TN, located near the 1-24/I-75 split."
        },
        {
          "type": "locations",
          "label": "Office Locations",
          "background": "alt",
          "anchorId": "office-locations",
          "displayMode": "cards",
          "layoutMode": "top",
          "featureSide": "right",
          "mapMode": "linkout",
          "maxCols": 2,
          "showHours": true,
          "items": [
            {
              "locationIndex": "0",
              "imagePath": "staff/office-ringgold-01.png"
            },
            {
              "locationIndex": "1",
              "imagePath": "staff/office-ooltewah-01.png"
            }
          ]
        },
        {
          "type": "locations",
          "label": "Hospital / Surgical Locations",
          "background": "dark",
          "anchorId": "other-locations",
          "displayMode": "feature",
          "layoutMode": "top",
          "featureSide": "left",
          "mapMode": "linkout",
          "maxCols": 2,
          "showHours": false,
          "items": [
            {
              "locationIndex": "2",
              "imagePath": "staff/office-parkridge east.png"
            },
            {
              "locationIndex": "3",
              "imagePath": "staff/office-physicians center.png"
            }
          ]
        }
      ]
    },
    {
      "slug": "services",
      "navLabel": "Services",
      "emoji": "👩‍⚕️",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "services",
          "label": "What We Can Do",
          "background": "light",
          "anchorId": "our-services",
          "heading": "Our Services",
          "subtitle": "",
          "maxCols": 3,
          "items": [
            {
              "icon": "👩‍⚕️",
              "title": "Gynecology",
              "desc": "The best treatment for disease is prevention. Our physicians encourage our patients to come for routine examinations on a regular basis.",
              "detail": "Your physician will advise how often you should schedule an appointment based on your personal medical history.",
              "btnLabel": "Gynecology Services",
              "btnLinkType": "internal",
              "btnLinkUrl": "gynecology",
              "btnAnchorId": "",
              "imagePath": "images/GYNECOLOGY.webp",
              "imageSize": "full"
            },
            {
              "icon": "👶",
              "title": "Obstetrics",
              "desc": "Our practice cares for a woman’s unique needs in a warm, courteous and professional environment. Our dedication to excellence in care during pregnancy, labor and delivery, and postpartum means we will keep you surrounded by the best medical team available in the area. During your pregnancy, we will closely monitor your progress to ensure the best possible quality of care, striving for a healthy baby and mother.",
              "detail": "We provide a large selection of prenatal services – from routine care for the healthy mother to the most sophisticated care for the complicated pregnancy. Our clinical team works together with specialists in maternal fetal medicine to provide care for our patients with high-risk problems in pregnancy. These specialists can manage the most complicated pregnancies and perform CVS, amniocentesis, percutaneous umbilical cord sampling, Level II Ultrasound, and Doppler Flow studies.",
              "btnLabel": "Obstetrical Services",
              "btnLinkType": "internal",
              "btnLinkUrl": "obstetrics",
              "btnAnchorId": "",
              "imagePath": "images/obstetrics-01.png",
              "imageSize": "full"
            },
            {
              "icon": "🩺",
              "title": "Surgeries",
              "desc": "Our physicians offer a full spectrum of female health procedures and surgeries.  We will discuss your surgical treatment plan with you and come up with the best solution for you.",
              "detail": "Some procedures are offered in the office while others will be performed at Parkridge East Hospital or Physicians Surgery Center.  Our administrative staff will help you navigate your insurance benefits to ensure no unexpected bills. We accept all major commercial health insurances, Medicare, and Medicaid. Affordable payment plans available.",
              "btnLabel": "Surgical Services",
              "btnLinkType": "internal",
              "btnLinkUrl": "surgery",
              "btnAnchorId": "",
              "imagePath": "images/surgery-01.png",
              "imageSize": "full"
            },
            {
              "icon": "🏵️",
              "title": "Aesthetics",
              "desc": "Here at Aesthetic Therapy we focus on creating an environment that is relaxing and catered to your needs.",
              "detail": "Treatments include Facial Treatments, Dermaplaning Treatment, Hydrofacial Treatment, Spray Tans, Body treatments,\nVaginal Rejuvenation, Botox Injections, and Microneedling. Treatment Packages are available.",
              "btnLabel": "Visit Aesthetics",
              "btnLinkType": "external",
              "btnLinkUrl": "home",
              "btnAnchorId": "",
              "imagePath": "images/aesthetics-01.png",
              "imageSize": "full"
            }
          ]
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "none",
          "primary_linkLabel": "",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "internal",
          "secondary_linkLabel": "Contact Us",
          "secondary_linkUrl": "forms",
          "secondary_anchorId": ""
        }
      ]
    },
    {
      "slug": "gynecology",
      "navLabel": "Gynecology",
      "emoji": "👩‍⚕️",
      "enabled": true,
      "parent": "services",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Service",
          "background": "alt",
          "anchorId": "gynecology",
          "heading": "Gynecology",
          "body": "The best treatment for disease is prevention. Our physicians encourage our patients to come for routine examinations on a regular basis. Your physician will advise how often you should schedule an appointment based on your personal medical history.  A few of our specialities include the following:",
          "imagePath": "images/GYNECOLOGY.webp",
          "imagePosition": "right",
          "imageMaxWidth": "",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "checklist",
          "label": "",
          "background": "light",
          "anchorId": "gyn-care",
          "heading": "Gyn Care",
          "subtitle": "",
          "fullWidth": false,
          "categories": [
            {
              "title": "Schedule an appointment for:",
              "items": [
                "Abnormal pap smear management and colposcopy",
                "Adolescent Screening",
                "Breast and ovarian cancer screening",
                "Endometriosis diagnosis and management",
                "Benign Breast Disease",
                "Cervical Cancer Vaccine",
                "Menstrual Cramping",
                "Heavy Periods",
                "Hormone replacement therapy",
                "Irregular period treatments",
                "Management of HPV",
                "Menopausal Care",
                "Ovarian cysts",
                "Painful intercourse",
                "Pelvic pain",
                "PMS management",
                "STD Screening and Treatment",
                "Urinary incontinence evaluation and treatment",
                "Urodynamics Testing",
                "Vulvar disorders"
              ]
            }
          ]
        },
        {
          "type": "checklist",
          "label": "",
          "background": "light",
          "anchorId": "family-planning",
          "heading": "Family Planning",
          "subtitle": "",
          "fullWidth": false,
          "categories": [
            {
              "title": "We offer family assistance:",
              "items": [
                "Infertility",
                "Contraception Care and Management",
                "Intrauterine Systems (IUDs)",
                "Nexplanon",
                "Permanent Birth Control – Tubal Ligation",
                "Natural Family Planning"
              ]
            }
          ]
        },
        {
          "type": "checklist",
          "label": "",
          "background": "light",
          "anchorId": "women-care",
          "heading": "Well Women Care",
          "subtitle": "",
          "fullWidth": false,
          "categories": [
            {
              "title": "Yearly Checkups:",
              "items": [
                "Annual Exams",
                "Cervical cancer screening",
                "HPV screening and management",
                "Breast Exams",
                "Pelvic Exams",
                "Adolescent gyn and counseling",
                "Fitness / dietary/ nutrition counseling",
                "Mammography",
                "Osteoporosis prevention, screening, and management",
                "GYN Ultrasound Services"
              ]
            }
          ]
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "none",
          "primary_linkLabel": "",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "internal",
          "secondary_linkLabel": "Want More Information?",
          "secondary_linkUrl": "forms",
          "secondary_anchorId": ""
        }
      ]
    },
    {
      "slug": "obstetrics",
      "navLabel": "Obstetrics",
      "emoji": "📄",
      "enabled": true,
      "parent": "services",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Service",
          "background": "alt",
          "anchorId": "obstetrics",
          "heading": "Obstetrics",
          "body": "Our practice cares for a woman’s unique needs in a warm, courteous and professional environment. Our dedication to excellence in care during pregnancy, labor and delivery, and postpartum means we will keep you surrounded by the best medical team available in the area. During your pregnancy, we will closely monitor your progress to ensure the best possible quality of care, striving for a healthy baby and mother.\n\nWe provide a large selection of prenatal services – from routine care for the healthy mother to the most sophisticated care for the complicated pregnancy. Our clinical team works together with specialists in maternal fetal medicine to provide care for our patients with high-risk problems in pregnancy. These specialists can manage the most complicated pregnancies and perform CVS, amniocentesis, percutaneous umbilical cord sampling, Level II Ultrasound, and Doppler Flow studies.",
          "imagePath": "images/obstetrics-01.png",
          "imagePosition": "right",
          "imageMaxWidth": "",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "two-col",
          "label": "",
          "background": "light",
          "anchorId": "obstetrical-care",
          "heading": "Obstetrical Care",
          "body": "Preconception counseling and testing\n\nPrenatal care\n\nLow risk and high risk Pregnancy\n\nMidwifery services\n\nIn-office Ultrasound\n\nIn-office fetal non-stress testing\n\nIn-office Fetal biophysical profile testing\n\nMultiple gestation pregnancies\n\nOB Ultrasound Services\n\nEarly Ob ultrasound\n\n18 – 20 wk Ob ultrasound for fetal assessment\n\n3D/4D Ultrasound\n\nLab work done on premises",
          "imagePath": "images/obstetrics-02.png",
          "imagePosition": "left",
          "imageMaxWidth": "",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "two-col",
          "label": "",
          "background": "light",
          "anchorId": "two-col",
          "heading": "",
          "body": "Gestational Hypertension\n\nGestational Diabetes\n\nAdvanced maternal age\n\nPreterm labor\n\nPremature rupture of membranes\n\nHistory of incompetent cervix\n\nMaternal medical problems\n\nChronic hypertension\n\nRespiratory disease (PE, Asthma, etc.)\n\nGI disease (Crohns, Celiac, etc.)\n\nHematologic (Sickle Cell, cardiolipin Ab, etc.)\n\nPre-existing diabetes\n\nMale infant circumcision",
          "imagePath": "images/obstetrics-03.png",
          "imagePosition": "right",
          "imageMaxWidth": "",
          "cta_linkType": "none",
          "cta_linkUrl": "forms",
          "cta_linkLabel": ""
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "none",
          "primary_linkLabel": "",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "internal",
          "secondary_linkLabel": "Want More Information?",
          "secondary_linkUrl": "forms",
          "secondary_anchorId": ""
        }
      ]
    },
    {
      "slug": "surgery",
      "navLabel": "Surgery",
      "emoji": "📄",
      "enabled": true,
      "parent": "services",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Service",
          "background": "light",
          "anchorId": "two-col",
          "heading": "Surgical Services",
          "body": "Our physicians offer a full spectrum of female health procedures and surgeries.  We will discuss your surgical treatment plan with you and come up with the best solution for you. Some procedures are offered in the office while others will be performed at Parkridge East Hospital or Physicians Surgery Center.  Our administrative staff will help you navigate your insurance benefits to ensure no unexpected bills. We accept all major commercial health insurances, Medicare, and Medicaid. Affordable payment plans available.",
          "imagePath": "images/surgery-01.png",
          "imagePosition": "right",
          "imageMaxWidth": "",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "richtext",
          "label": "",
          "background": "light",
          "anchorId": "richtext",
          "richContent": "<h3>Laparoscopic And Laser Surgery</h3><p>Laparoscopy&nbsp;is the most common procedure used to diagnose and remove endometriosis. Instead of using a large abdominal incision, the surgeon inserts a lighted viewing instrument called a laparoscope through a small incision.&nbsp;</p><h3>In-Office Ablation</h3><p>NovaSure®&nbsp;is a quick, safe, and simple procedure to lighten or stop your periods, without the side effects of hormones or the risks of hysterectomy.&nbsp;</p><h3>In-Office Hysteroscopy</h3><p>Hysteroscopy is the process of viewing and operating in the endometrial cavity from a transcervical approach.</p><!--EndFragment-->\n\n",
          "imagePath": "",
          "imagePos": "none",
          "imageSize": "md",
          "imageCaption": "",
          "fullWidth": false
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "none",
          "primary_linkLabel": "",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "internal",
          "secondary_linkLabel": "Want More Information?",
          "secondary_linkUrl": "forms",
          "secondary_anchorId": ""
        }
      ]
    },
    {
      "slug": "patients",
      "navLabel": "Patients",
      "emoji": "📄",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "bullets",
          "label": "Visit Preparation",
          "background": "dark",
          "anchorId": "patient-information",
          "heading": "Patient Information",
          "subtitle": "",
          "fullWidth": false,
          "items": [
            {
              "icon": "✓",
              "title": "Patient Portal",
              "desc": "Update forms, message your provider, see test results and more are available on our patient portal. New patients can create a account and fill out forms before your first visit.",
              "linkType": "external",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "icon": "✓",
              "title": "Office Locations",
              "desc": "",
              "linkType": "internal",
              "linkUrl": "home",
              "anchorId": "locations"
            }
          ]
        }
      ]
    },
    {
      "slug": "forms",
      "navLabel": "Forms",
      "emoji": "📄",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "form",
          "label": "Contact Form",
          "background": "alt",
          "anchorId": "form-services",
          "heading": "Services",
          "intro": "Reach out and let us know what you would like more information about.",
          "submitLabel": "Send Message",
          "successMsg": "Thank you! We'll be in touch soon.",
          "endpoint": "",
          "fields": [
            {
              "type": "text",
              "label": "First Name",
              "placeholder": "e.g. Jane",
              "required": true,
              "halfWidth": true,
              "options": []
            },
            {
              "type": "text",
              "label": "Last Name",
              "placeholder": "e.g. Smith",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "email",
              "label": "Email",
              "placeholder": "",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "phone",
              "label": "Phone Number",
              "placeholder": "",
              "required": false,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "checkbox",
              "label": "Services:",
              "placeholder": "",
              "required": false,
              "halfWidth": false,
              "options": [
                "Obstetric Services",
                "Gynecology Services",
                "Aesthetics Services",
                "Other"
              ]
            },
            {
              "type": "radio",
              "label": "Location",
              "placeholder": "",
              "required": true,
              "halfWidth": false,
              "options": [
                "Ringgold",
                "Ooltewah"
              ]
            },
            {
              "type": "textarea",
              "label": "Message (optional)",
              "placeholder": "Have any questions or feedback?",
              "required": false,
              "halfWidth": false,
              "options": []
            }
          ]
        },
        {
          "type": "form",
          "label": "",
          "background": "dark",
          "anchorId": "form-photo-release",
          "heading": "Photo Release Form",
          "intro": "Release\nI, (the “Releasor”) grant permission and consent to Associates in Women's Health (the “Releasee”)\nfor the use of the following photograph(s) as identified below for presentation under any legal\ncondition, including but not limited to: publicity, copyright purposes, illustration, advertising, and\nweb content: Description: Pictures of minor child\nI understand that there shall be no payment for this release.\nI understand that no royalty, fee, or other compensation shall become payable to me by reason of\nsuch use.\nI, the Releasee, understand and agree to the aforementioned terms and conditions.",
          "submitLabel": "Submit",
          "successMsg": "Thank you! We'll be in touch soon.",
          "endpoint": "",
          "fields": [
            {
              "type": "checkbox",
              "label": "",
              "placeholder": "",
              "required": true,
              "halfWidth": false,
              "options": [
                "Accept"
              ]
            },
            {
              "type": "text",
              "label": "First Name",
              "placeholder": "",
              "required": true,
              "halfWidth": true,
              "options": []
            },
            {
              "type": "text",
              "label": "Last Name",
              "placeholder": "",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "email",
              "label": "Email Address",
              "placeholder": "",
              "required": true,
              "halfWidth": false,
              "options": []
            }
          ]
        },
        {
          "type": "text",
          "label": "",
          "background": "alt",
          "anchorId": "form-patient-demographics",
          "heading": "Patient Demographics Form",
          "body": "All current patients must complete this form every year. Sorry, it’s not our rule."
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button-2",
          "primary_linkType": "file",
          "primary_linkLabel": "Patient Demographics Form",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "none",
          "secondary_linkLabel": "",
          "secondary_linkUrl": "",
          "secondary_anchorId": ""
        },
        {
          "type": "text",
          "label": "",
          "background": "alt",
          "anchorId": "form-medical-records",
          "heading": "Medical Records Release",
          "body": ""
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "file",
          "primary_linkLabel": "Medical Records Release",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "none",
          "secondary_linkLabel": "",
          "secondary_linkUrl": "",
          "secondary_anchorId": ""
        },
        {
          "type": "text",
          "label": "",
          "background": "alt",
          "anchorId": "form-privacy-hippa",
          "heading": "Privacy & HIPPA",
          "body": ""
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button-3",
          "primary_linkType": "file",
          "primary_linkLabel": "Privacy & HIPPA Forms",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "none",
          "secondary_linkLabel": "",
          "secondary_linkUrl": "",
          "secondary_anchorId": ""
        }
      ]
    },
    {
      "slug": "faq",
      "navLabel": "FAQ",
      "emoji": "❓",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "text",
          "label": "Need Help?",
          "background": "light",
          "anchorId": "frequently-asked-questions",
          "heading": "Frequently Asked Questions",
          "body": "These are a few of the most frequently questions with answers that our providers are asked. Please look for your question here or use the search box above before calling the office.  *The questions and answers are not exhaustive and do not constitute medical advice. They are intended for general information and do not take into account your person history or situation.  If you have a question you would like to ask, please use the form below. Check back often to see new questions & the answers!"
        },
        {
          "type": "faq",
          "label": "",
          "background": "alt",
          "anchorId": "faq-general",
          "heading": "General Questions",
          "subtitle": "",
          "fullWidth": true,
          "items": [
            {
              "q": "Where Are My Lab or Test Results?",
              "a": "Lab & test results can be found by visiting the patient portal or calling the office during regular business hours. \n\nNO RESULTS WILL BE GIVEN AFTER BUSINESS HOURS.",
              "linkLabel": "Patient Portal",
              "linkType": "internal",
              "linkUrl": "patients",
              "anchorId": "patient-information"
            },
            {
              "q": "How do i refill my medications?",
              "a": "Medication refills can be requested by visiting the patient portal or calling the office during regular business hours. \n\nNO REFILLS WILL BE CALLED IN AFTER BUSINESS HOURS.",
              "linkLabel": "Patient Portal",
              "linkType": "internal",
              "linkUrl": "patients",
              "anchorId": "patient-information"
            },
            {
              "q": "How Do I Make, Change, or Cancel My Appointment?",
              "a": "Appointments can be made, changed, or cancelled by making a request through the patient portal or calling the office during regular business hours. \n\nNO APPOINTMENTS WILL BE MADE, CHANGED, OR CANCELLED AFTER BUSINESS HOURS.",
              "linkLabel": "Patient Portal",
              "linkType": "internal",
              "linkUrl": "patients",
              "anchorId": "patient-information"
            },
            {
              "q": "What are the risks factors of hysterectomy surgery?",
              "a": "Hysterectomies are a fairly common procedure, as such surgeons are highly skilled in the procedure. Complications may include blood loss, infection, or a negative reaction to anesthesia. These are common with all forms of surgery. During the surgery, there is also a risk that other organs may be affected, because the pelvic region is a very tight operating environment. As such, patients may have to have follow-up surgery to correct any damage done to other organs.  Specific risks can be more or less depending on the type of hysterectomy you are having.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "I’m going to the hospital, what do i need to do?",
              "a": "GO!\n\nThe hospital will call the physician on call. Please do not call the doctor, hospital, or office to tell them you are coming. We do not have call ahead seating.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            }
          ]
        },
        {
          "type": "faq",
          "label": "",
          "background": "light",
          "anchorId": "faq-pregnancy",
          "heading": "Pregnancy Questions",
          "subtitle": "",
          "fullWidth": true,
          "items": [
            {
              "q": "What medications (allergies, cold/flu) can I take during pregnancy?",
              "a": "Knowing what you can and cannot take when you are taking medicine for two can be difficult. This is a list of medications it is safe to take as long as you are having a normal pregnancy. Whether you are pregnant or not, generics can be substituted for name brands, unless your physician says otherwise.\n\nAllergy Symptoms: Benedryl, or Cortaid\n\nCongestion: Sudafed, Actifed, or Mucinex\n\nConstipation: Metemucil, Colace, or Milk of Magnesia\n\nCough/Chest: Robitussin DM or Triaminic\n\nDiarrhea: Immodium\n\nFever: Tylenol (2 regular strength)\n\nHeadache: Tylenol (2 regular strength)\n\nHeartburn: Maalox, Mylanta, Kudrox, Rolaids, or Tums\n\nHemorrhoids: Preparation H, or Anusol\n\nNausea: Emetrol\n\nPain: Tylenol (2 regular strength)\n\nYeast: Gynelotrimin, Mycelex (May use vaginal applicator unless you have been told not to have anything in the vagina), or Monistat (okay after 3rd month)",
              "linkLabel": "Pregnancy Meds - YouTube",
              "linkType": "external",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "What should I be aware of during a summer pregnancy?",
              "a": "Hydration: Due to the summer heat, water intake is critical. Pregnant women are advised to drink two quarts of water daily.\n\nSun Safety: Pregnant women are more susceptible to sunburns, even if they typically tan easily. The video strongly recommends using a high-quality sunscreen whenever going out in the sun to prevent skin damage.",
              "linkLabel": "Summer Pregnancy - YouTube",
              "linkType": "external",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "I lost my mucus plug! What do I do?",
              "a": "Nothing.  It is fine.  \n\nEveryone loses it at some point.  Seeing a little blood streak with it is also common, but no worries.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "Is vaginal bleeding during pregnancy okay?",
              "a": "Seeing a little 'pink' on toilet paper when you go to the bathroom is quite common in pregnancy and rarely is it anything to be concerned with.  It is commonly seen after intercourse, if you have a cerclage, or if you have a vaginal discharge.  \n\nLet your provider know at your next appointment.  \n\nIf it continues and gets heavier like a period let your provider know soon or go to an emergency room.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "How do i know if i’m having Braxton Hicks or ‘real’ labor contractions?",
              "a": "In general, true labor contractions come at predictable intervals (ie, every 5 minutes), last 1-2 minutes, causes the whole tummy to get real firm and tight, and progressively get worse.  False labor or Braxton Hicks contractions is anything else, they are random, irregular, short lived, happen anywhere in the abdomen, and are a nuisance.  \n\nYou should call your provider or go to labor and delivery if you have 10 or more true contractions per hour for at least an hour or longer.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "What is the difference between a DO & an MD?",
              "a": "Medical Equivalence: Both MDs and DOs are fully licensed physicians who practice medicine in every field and have equal professional standing.\n\nDefining the Degrees: An MD is trained in allopathic medicine, while a DO is a Doctor of Osteopathy.\n\nDifferent Training Focus: While both are trained to treat patients effectively, DO schools provide additional training that emphasizes a holistic approach.\n\nHolistic Treatment: A DO is trained to treat the entire patient, considering their mental, physical, spiritual, and emotional health.\n\nHands-on Techniques: DOs receive specialized training in musculoskeletal manipulative techniques, which the doctor compares to those used by chiropractors, to provide additional hands-on care for patients.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "What is endometriosis and how would I know if i have it?",
              "a": "Endometriosis is a condition in which tissue that normally lines the inside of the uterus (the endometrium) spreads and implants in areas outside of the uterus. Often the site of the implantation is somewhere in the abdominal cavity. In patients with endometriosis, these implants of endometrium grow on a cyclic basis just as the normal endometrium does. When the normal endometrium sheds during your menstrual cycle causing your period, so do these endometrial implants. They can cause a small amount of bleeding within your abdominal cavity which results in pain.\n\nSymptoms of endometriosis are often described as menstrual cramping and pain that begins before the onset of menstrual bleeding, and continues through the menstrual cycle. The severity of endometriosis often does not correlate with the degree of pain experienced with endometriosis. Often women with a small amount of endometriosis will have significant cyclic pain, and often women with a large amount of endometriosis will have minimal pain. Endometriosis is often seen in women who previously had pain-free menstrual cycles, and have gradually noticed a worsening in their pain.\n\nThe definitive diagnosis of endometriosis can only be made through surgery where the endometriotic lesions can be seen and sometimes biopsied to make the diagnosis.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "What are benefits and risks of tubal reversal?",
              "a": "The most obvious benefit of tubal ligation reversal is the opportunity to become pregnant and have a baby. Another benefit is the relief of post-tubal ligation symptoms. Some women have the ligation reversal in order to restore their sense of being “whole again”, and others for relief of guilt and/or to be consistent with religious beliefs. Many women have told me that they felt the sterilization operation took away what they felt is in God’s domain to decide about whether or not they would have any more children.\n\nThere are risks associated with any surgical procedure, but these are minimal. The primary risk of tubal ligation reversal is the long-term risk of tubal or ectopic pregnancy. It is estimated that the baseline 2-3% risk of ectopic pregnancy in the general population of women who have not had a tubal sterilization is increased to 10-15% after reversal of tubal ligation.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "What is HPV?",
              "a": "Human PapillomaVirus (HPV) is a very common infection that can be spread through sexual contact. Studies suggest that three of every four people who have sex will get a genital HPV infection at some point in their lives. Sexually transmitted HPV can be spread through vaginal, anal, and oral sex. Some types of HPV can cause cancer of the cervix, vulva, vagina, and penis.Genital warts are not usually linked with cancer. To lower your risk of developing HPV, limit your number of sexual partners and use condoms. If you are between the ages of 9-26, you should have the HPV vaccine to help protect you from infection. Regular pap tests are the best way to prevent precancer and cancer of the cervix.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "Should my child get the HPV vaccine?",
              "a": "Recommendation: The vaccine is recommended for all teenagers, both boys and girls, between the ages of 9 and 26.\n\nPurpose: The HPV virus is identified as the primary cause of cervical cancer; vaccination can prevent up to 80% of these cases.\n\nSafety and Efficacy: The vaccine has been in use since the 1990s, is considered highly effective, and has an excellent safety profile.\n\nSide Effects: Dr. T notes that there are very few side effects beyond common reactions like pain at the injection site.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "I'm having pain in (lower back, pelvis, vagina), what do I do?",
              "a": "Growing another human is not easy…that’s why women do it!\n\nIt is very common to experience pain & pressure as your body adjusts and grows to accommodate a growing baby - especially in your low back, pelvis, and vagina. \n\nWhat can I take?  Tylenol is safe during pregnancy, as well as muscle ache creams or patches such as Icy Hot or Salonpas. Anything stronger would require a prescription and cannot be called in per federal law.  Narcotics cannot be called in per federal law and are not a good idea for your baby. See also medications while pregnant page.\n\nWhat can I do?  \n\nMedicated Patches \n\nStretching\n\nPregnancy Yoga\n\nBelly Belt \n\nGetting in a Pool \n\nTylenol\n\nWarm baths \n\nHeating Pad (medium or low heat)\n\nMassage\n\nChiropractic Care\n\nMuscle Ache Creams \n\nShooting pains in vagina and a lot of pressure in low pelvis in the third trimester is common and is called \"lightning\".  It is due to the baby dropping into the pelvis.  There isn't anything to make it go away, unfortunately, just try getting off your feet and rest.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            },
            {
              "q": "When Should I Feel My Baby Moving?",
              "a": "In general not feeling your baby move or move consistently before 24 weeks is never a concern.  The baby is very small and can get into positions where you can't feel it well, even if you were feeling it well previously.  \n\nAs the pregnancy progresses you should feel the baby move at least 10 times in a given hour or two at least 2 different times in a 24 hour period.  \n\nMany times as you get towards the very end of pregnancy the baby's movements are not as dramatic or as frequent as the baby has less room to move and is starting to learn how to sleep for longer periods of time.",
              "linkLabel": "",
              "linkType": "none",
              "linkUrl": "home",
              "anchorId": ""
            }
          ]
        }
      ]
    }
  ],
  "aboutSections": [
    {
      "type": "gallery",
      "label": "Office Staff",
      "background": "alt",
      "anchorId": "staff-ringgold",
      "heading": "Ringgold Office Support Staff",
      "subtitle": "",
      "galleryCols": 3,
      "items": [
        {
          "imagePath": "staff/ringgold-01.png",
          "alt": "",
          "title": "",
          "caption": ""
        },
        {
          "imagePath": "staff/ringgold-02.png",
          "alt": "",
          "title": "",
          "caption": ""
        },
        {
          "imagePath": "staff/ringgold-03.png",
          "alt": "",
          "title": "",
          "caption": ""
        }
      ]
    },
    {
      "type": "gallery",
      "label": "",
      "background": "light",
      "anchorId": "staff-ooltewah",
      "heading": "Ooltewah Office Support Staff",
      "subtitle": "",
      "galleryCols": 3,
      "items": [
        {
          "imagePath": "staff/ooltewah-01.png",
          "alt": "",
          "title": "",
          "caption": ""
        },
        {
          "imagePath": "staff/ooltewah-02.png",
          "alt": "",
          "title": "",
          "caption": ""
        },
        {
          "imagePath": "staff/ooltewah-03.png",
          "alt": "",
          "title": "",
          "caption": ""
        }
      ]
    }
  ],
  "homeSections": [
    {
      "type": "team",
      "label": "",
      "background": "alt",
      "anchorId": "our-physicians",
      "heading": "Our Physicians",
      "items": []
    },
    {
      "type": "button",
      "label": "",
      "background": "light",
      "anchorId": "button",
      "primary_linkType": "none",
      "primary_linkLabel": "",
      "primary_linkUrl": "about",
      "primary_anchorId": "",
      "secondary_linkType": "internal",
      "secondary_linkLabel": "Learn More About Us",
      "secondary_linkUrl": "about",
      "secondary_anchorId": ""
    },
    {
      "type": "locations",
      "label": "Our Locations",
      "background": "alt",
      "anchorId": "locations",
      "items": [
        {
          "locationIndex": "0",
          "imagePath": "staff/office-ringgold-01.png"
        },
        {
          "locationIndex": "1",
          "imagePath": "staff/office-ooltewah-01.png"
        }
      ],
      "displayMode": "cards",
      "layoutMode": "top",
      "featureSide": "right",
      "mapMode": "linkout",
      "maxCols": 2,
      "showHours": false
    },
    {
      "type": "button",
      "label": "",
      "background": "light",
      "anchorId": "button-2",
      "primary_linkType": "internal",
      "primary_linkLabel": "Contact Us",
      "primary_linkUrl": "contact",
      "primary_anchorId": "",
      "secondary_linkType": "none",
      "secondary_linkLabel": "",
      "secondary_linkUrl": "home",
      "secondary_anchorId": ""
    }
  ],
  "footerBio": "",
  "animateStats": false,
  "contactSubmitLabel": "Submit",
  "contactSuccessMsg": "",
  "search": {
    "placeholder": "Search...",
    "noResultsMessage": "No results for '{query}'",
    "noResultsSubtext": "Try a different search term.",
    "resultsPerPage": 5,
    "excludedPages": []
  },
  "siteAccess": "public",
  "sessionDays": 7,
  "pinPad": {
    "headline": "Members Only",
    "subtext": "Restricted Access",
    "wrongMsg": "Incorrect PIN. Try again.",
    "theme": "dark",
    "lockEmoji": "🔒",
    "backLabel": "← Back to Home",
    "maxAttempts": 3,
    "welcomeMsg": "Welcome back, {name}",
    "commissionerMsg": "Commissioner Access Granted",
    "welcomeDuration": 2,
    "showImposter": true,
    "imposterHeadline": "ACCESS DENIED",
    "imposterMsg": "This attempt has been logged.",
    "imposterDuration": 3
  },
  "members": [],
  "pageAccess": {
    "home": "public",
    "about": "public",
    "cp-0": "public",
    "cp-1": "public",
    "cp-2": "public",
    "cp-3": "public",
    "cp-4": "public",
    "cp-5": "public",
    "cp-6": "public",
    "cp-7": "public"
  },
  "_savedAt": 1777719389373,
  "mapsApiKey": ""
};
