/**
 * ============================================================
 * ASSOCIATES IN WOMENS HEALTH — SITE CONFIGURATION
 * ============================================================
 * Generated by Site Admin on May 1, 2026
 *
 * HOW TO USE:
 *   1. Save this file as config.js in your website folder
 *   2. Make sure index.html loads it: <script src="config.js"></script>
 *   3. Reload the website — your changes appear automatically
 * ============================================================
 */

const SITE_CONFIG = {
  "firmName": "Associates in Womens Health",
  "tagline": "",
  "preloaderTagline": "",
  "logoPrimary": "logos/AWH Logo-pinkwht.png",
  "logoAlternate": "logos/AWH Logo-wht.png",
  "logoHeaderChoice": "primary",
  "logoHeaderHeight": 60,
  "logoSplashChoice": "primary",
  "logoSplashHeight": 200,
  "logoSplashMode": "logo-only",
  "logoFooterChoice": "alternate",
  "logoFooterHeight": 80,
  "pageHeaders": {
    "about": {
      "label": "Meet the Team",
      "title": "the Physicians",
      "subtitle": ""
    },
    "contact": {
      "label": "Get in Touch"
    }
  },
  "attorneyName": "Dr. Matthew  Roberts, DO",
  "attorneyDegree": "DO, West Virginia School of Osteopathic Medicine, 1987",
  "attorneyCredentials": [
    "• American College of Osteopathic Obstetricians and Gynecologists, Member",
    "• American Osteopathic Association, Member",
    "• Tennessee Medical Association, Member",
    "• Women’s Health Services, President"
  ],
  "aboutBio1": "Dr. Matthew Roberts has been in practice since 1992, and on staff with Associates in Women’s Health since 1996.  He is licensed in both Tennessee and Georgia, seeing patients at both Associates in Women’s Health’s locations.",
  "aboutBio2": "He is originally from Murfreesboro, TN and presently resides in McDonald, TN with his wife, Wendy, and three children, Devin, Macey & Chase.",
  "attorneyPhoto": "staff/roberts-01.png",
  "aboutNavLabel": "Meet the Team",
  "attorneys": [
    {
      "name": "Dr. Matthew  Roberts, DO",
      "degree": "DO, West Virginia School of Osteopathic Medicine, 1987",
      "education": [
        "DO, West Virginia School of Osteopathic Medicine, 1987",
        "Middle Tennessee State University B.S. Degree, 1987"
      ],
      "photo": "staff/roberts-01.png",
      "credentials": [
        "• American College of Osteopathic Obstetricians and Gynecologists, Member",
        "• American Osteopathic Association, Member",
        "• Tennessee Medical Association, Member",
        "• Women’s Health Services, President"
      ],
      "bio1": "Dr. Matthew Roberts has been in practice since 1992, and on staff with Associates in Women’s Health since 1996.  He is licensed in both Tennessee and Georgia, seeing patients at both Associates in Women’s Health’s locations.",
      "bio2": "He is originally from Murfreesboro, TN and presently resides in McDonald, TN with his wife, Wendy, and three children, Devin, Macey & Chase.",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    },
    {
      "name": "Dr. Terry L. Williams, Jr. DO",
      "degree": "DO, West Virginia School of Osteopathic Medicine, 2004",
      "education": [
        "DO, West Virginia School of Osteopathic Medicine, 2004",
        "UT, Chattanooga Master’s Degree in Education, 1995",
        "Auburn University B.S. Degree in Education, 1992"
      ],
      "photo": "staff/williams-01.png",
      "credentials": [
        "• American College of Osteopathic Obstetricians and Gynecologists, Member",
        "• American Osteopathic Association, Member",
        "• Tennessee Medical Association, Member",
        "• Berlex Best Teaching Resident Award",
        "• W. Powell Hutcherson Award for Best Resident",
        "• APGO Excellence in Teaching Award"
      ],
      "bio1": "Dr. Williams joined Associates in Women’s Health in August 2016. He spent the previous 5 years in private practice in Ashe County, North Carolina.",
      "bio2": "Dr. Williams is an expert in the da Vinci robotic surgical system for multiple gynecological surgeries.\n\nHe is originally from the East Brainerd area, and currently resides in Ringgold, GA with his wife, Jenny and 3 children, Maggie, Ty, & Molly Beth.",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    },
    {
      "name": "Heidi Septor, MSN, FNP-C, MSCP",
      "degree": "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
      "education": [
        "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
        "UT, Chattanooga Bachelor of Science in Nursing, 2013 - Summa Cum Laude"
      ],
      "photo": "staff/septor-01.png",
      "credentials": [
        "Sigma Theta Tau International Honor Society Member",
        "SALUTE Veterans National Honor Society Member",
        "American Academy of Nurse Practitioners",
        "Daisy Award Winner"
      ],
      "bio1": "Heidi joined Associates of Women's Health in 2021. Heidi's journey began in 2002 when she enlisted in the Army and served as a combat medic, where her passion for helping others took flight. She worked as a paramedic and later a Registered Nurse.",
      "bio2": "During her deployment to Iraq, Heidi was recognized for her bravery and expertise, earning the Air Medal and the Combat Action Badge. After a fulfilling career, including serving as a Captain, she retired from the Army in 2024.\nOriginally from Massachusetts, Heidi has also called Texas and Florida home, and now has built a life in Georgia. With her wealth of experience and compassionate approach, Heidi is here to support and empower our patients every step of the way.",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    },
    {
      "name": "Hannah White, FNP",
      "degree": "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
      "education": [
        "UT, Chattanooga Master of Science in Nursing, Family Nurse Practitioner, 2019",
        "UT, Chattanooga Bachelor of Science in Nursing, 2013 - Summa Cum Laude"
      ],
      "photo": "staff/white-01.png",
      "credentials": [
        "• Sigma Theta Tau International Honor Society",
        "• American Association of Nurse Practitioners",
        "• Chattanooga Area Nurses in Advanced Practice"
      ],
      "bio1": "",
      "bio2": "",
      "socialLinks": [],
      "btnLabel": "",
      "btnLinkType": "none",
      "btnLinkUrl": ""
    }
  ],
  "phone": "(706) 861-4508",
  "phoneRaw": "17068614508",
  "fax": "",
  "email": "contact@awhealth.com",
  "address": "93 Robin Rd.",
  "city": "Ringgold",
  "state": "Georgia",
  "stateAbbr": "GA",
  "zip": "30736",
  "locations": [
    {
      "name": "Ringgold Office",
      "phone": "(706) 861-4508",
      "phoneRaw": "17068614508",
      "fax": "",
      "email": "contact@awhealth.com",
      "address": "93 Robin Rd.",
      "city": "Ringgold",
      "state": "Georgia",
      "stateAbbr": "GA",
      "zip": "30736",
      "hours": []
    },
    {
      "name": "Ooltewah Office",
      "phone": "(423) 910-0896",
      "phoneRaw": "14239100896",
      "fax": "",
      "email": "contact@awhealth.com",
      "address": "6845 Mountain View Rd.",
      "city": "Ooltewah",
      "state": "Tennessee",
      "stateAbbr": "TN",
      "zip": "37363",
      "hours": [
        {
          "days": "Monday - Thursday",
          "hours": "8.30 -4.00"
        },
        {
          "days": "Friday",
          "hours": "8.30 - 12.00"
        },
        {
          "days": "Closed Weekends",
          "hours": ""
        }
      ]
    }
  ],
  "hours": [],
  "socialLinks": [],
  "stats": [],
  "colors": {
    "navy": "#403749",
    "navyLight": "#403749",
    "gold": "#c358e9",
    "goldLight": "#43225d",
    "goldPale": "#faf6ec",
    "warmWhite": "#fffdf9",
    "cream": "#f9f6f0",
    "chrome": "#403749"
  },
  "fontColors": {
    "heading": "#000000",
    "body": "#000000",
    "onDark": "#ffffff",
    "onDarkMuted": "#f3f8fb"
  },
  "fontDisplay": "Merriweather",
  "fontBody": "Assistant",
  "metaDescription": "",
  "metaKeywords": "",
  "googleAnalyticsId": "",
  "formEndpoint": "",
  "pageTitles": {
    "home": "",
    "about": "",
    "contact": "",
    "privacy": ""
  },
  "heroBg": {
    "type": "video",
    "bgColor": "#0f2340",
    "imagePath": "",
    "imagePosition": "center center",
    "slides": [],
    "transition": "crossfade",
    "transitionSpeed": 2,
    "slideDuration": 8,
    "pauseOnHover": false,
    "showDots": true,
    "autoplay": true,
    "motionType": "zoom-out",
    "motionSpeed": 20,
    "overlayColor": "#0f2340",
    "overlayOpacity": 0.3,
    "videoClips": [
      {
        "mp4": "videos/hero-03.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 6
      },
      {
        "mp4": "videos/hero-00.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      },
      {
        "mp4": "videos/hero-01.mp4",
        "webm": "",
        "fallback": "",
        "transitionIn": "crossfade",
        "objectPosition": "center center",
        "playbackRate": 1,
        "startTime": 0,
        "playDuration": 0
      }
    ],
    "videoFallback": "",
    "videoTransSpeed": 3.9,
    "videoHoldEnabled": false,
    "videoHold": 4
  },
  "heroHeadline": "Associates in Women's Health",
  "heroSubline": "Associates in Women’s Health is an OB/GYN practice striving to provide the highest level of quality women’s healthcare to our patients. We do this by making our patients and their health our #1 priority. Our providers have extensive education, training, and experience to provide the very best medical care for women of all ages.  We are committed to providing quality women’s healthcare with individualized treatment plans for every patient.  ",
  "heroTrustBullets": [
    "2 Locations Serving GA & TN",
    "30+ Years of Experience"
  ],
  "heroPrimaryLabel": "Contact Us",
  "heroPrimaryLinkType": "internal",
  "heroPrimaryLinkUrl": "contact",
  "heroSecondaryLabel": "Our Services",
  "heroSecondaryLinkType": "internal",
  "heroSecondaryLinkUrl": "services",
  "whyChooseUs": {
    "heading": "",
    "subtext": "",
    "badgeNum": "",
    "badgeLabel": "",
    "bullets": []
  },
  "contactHeadline": "",
  "contactSubline": "",
  "contactFormHeading": "",
  "contactFormIntro": "",
  "contactPrivacyNote": "",
  "contactForm": [
    {
      "type": "text",
      "label": "First Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "text",
      "label": "Last Name",
      "placeholder": "",
      "required": true,
      "halfWidth": true,
      "options": []
    },
    {
      "type": "email",
      "label": "Email Address",
      "placeholder": "",
      "required": true,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "phone",
      "label": "Phone Number",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    },
    {
      "type": "textarea",
      "label": "Message",
      "placeholder": "",
      "required": false,
      "halfWidth": false,
      "options": []
    }
  ],
  "services": [],
  "faqs": [],
  "testimonials": [],
  "blogPosts": [],
  "processSteps": [],
  "processRequirements": [],
  "ctaLabel": "Contact Us",
  "pageToggles": {
    "about": true,
    "contact": true
  },
  "homeToggles": {
    "stats": true,
    "why": true,
    "testimonials": true
  },
  "customPages": [
    {
      "slug": "services",
      "navLabel": "Services",
      "emoji": "👩‍⚕️",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "services",
          "label": "What We Can Do",
          "background": "light",
          "anchorId": "our-services",
          "heading": "Our Services",
          "subtitle": "",
          "maxCols": 3,
          "items": [
            {
              "icon": "👩‍⚕️",
              "title": "Gynecology",
              "desc": "The best treatment for disease is prevention. Our physicians encourage our patients to come for routine examinations on a regular basis.",
              "detail": "Your physician will advise how often you should schedule an appointment based on your personal medical history.",
              "btnLabel": "Gynecology Services",
              "btnLinkType": "internal",
              "btnLinkUrl": "gynecology",
              "btnAnchorId": "",
              "imagePath": "",
              "imageSize": "thumb"
            }
          ]
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "none",
          "primary_linkLabel": "",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "internal",
          "secondary_linkLabel": "Contact Us",
          "secondary_linkUrl": "forms",
          "secondary_anchorId": "services"
        }
      ]
    },
    {
      "slug": "gynecology",
      "navLabel": "Gynecology",
      "emoji": "👩‍⚕️",
      "enabled": true,
      "parent": "services",
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "two-col",
          "label": "Service",
          "background": "alt",
          "anchorId": "gynecology",
          "heading": "Gynecology",
          "body": "The best treatment for disease is prevention. Our physicians encourage our patients to come for routine examinations on a regular basis. Your physician will advise how often you should schedule an appointment based on your personal medical history.  A few of our specialities include the following:",
          "imagePath": "images/GYNECOLOGY.webp",
          "imagePosition": "right",
          "imageMaxWidth": "",
          "cta_linkType": "none",
          "cta_linkUrl": "home",
          "cta_linkLabel": ""
        },
        {
          "type": "checklist",
          "label": "",
          "background": "light",
          "anchorId": "gyn-care",
          "heading": "Gyn Care",
          "subtitle": "",
          "fullWidth": false,
          "categories": [
            {
              "title": "Schedule an appointment for:",
              "items": [
                "Abnormal pap smear management and colposcopy",
                "Adolescent Screening",
                "Breast and ovarian cancer screening",
                "Endometriosis diagnosis and management",
                "Benign Breast Disease",
                "Cervical Cancer Vaccine",
                "Menstrual Cramping",
                "Heavy Periods",
                "Hormone replacement therapy",
                "Irregular period treatments",
                "Management of HPV",
                "Menopausal Care",
                "Ovarian cysts",
                "Painful intercourse",
                "Pelvic pain",
                "PMS management",
                "STD Screening and Treatment",
                "Urinary incontinence evaluation and treatment",
                "Urodynamics Testing",
                "Vulvar disorders"
              ]
            }
          ]
        },
        {
          "type": "checklist",
          "label": "",
          "background": "light",
          "anchorId": "family-planning",
          "heading": "Family Planning",
          "subtitle": "",
          "fullWidth": false,
          "categories": [
            {
              "title": "We offer family assistance:",
              "items": [
                "Infertility",
                "Contraception Care and Management",
                "Intrauterine Systems (IUDs)",
                "Nexplanon",
                "Permanent Birth Control – Tubal Ligation",
                "Natural Family Planning"
              ]
            }
          ]
        },
        {
          "type": "checklist",
          "label": "",
          "background": "light",
          "anchorId": "women-care",
          "heading": "Well Women Care",
          "subtitle": "",
          "fullWidth": false,
          "categories": [
            {
              "title": "Yearly Checkups:",
              "items": [
                "Annual Exams",
                "Cervical cancer screening",
                "HPV screening and management",
                "Breast Exams",
                "Pelvic Exams",
                "Adolescent gyn and counseling",
                "Fitness / dietary/ nutrition counseling",
                "Mammography",
                "Osteoporosis prevention, screening, and management",
                "GYN Ultrasound Services"
              ]
            }
          ]
        },
        {
          "type": "button",
          "label": "",
          "background": "light",
          "anchorId": "button",
          "primary_linkType": "none",
          "primary_linkLabel": "",
          "primary_linkUrl": "",
          "primary_anchorId": "",
          "secondary_linkType": "internal",
          "secondary_linkLabel": "Want More Information?",
          "secondary_linkUrl": "forms",
          "secondary_anchorId": "services"
        }
      ]
    },
    {
      "slug": "forms",
      "navLabel": "Forms",
      "emoji": "📄",
      "enabled": true,
      "parent": null,
      "hiddenFromNav": false,
      "sections": [
        {
          "type": "form",
          "label": "AWH Forms",
          "background": "alt",
          "anchorId": "services",
          "heading": "Services",
          "intro": "Reach out and let us know what you would like more information about.",
          "submitLabel": "Send Message",
          "successMsg": "Thank you! We'll be in touch soon.",
          "endpoint": "",
          "fields": [
            {
              "type": "text",
              "label": "First Name",
              "placeholder": "e.g. Jane",
              "required": true,
              "halfWidth": true,
              "options": []
            },
            {
              "type": "text",
              "label": "Last Name",
              "placeholder": "e.g. Smith",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "email",
              "label": "Email",
              "placeholder": "",
              "required": true,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "phone",
              "label": "Phone Number",
              "placeholder": "",
              "required": false,
              "halfWidth": false,
              "options": []
            },
            {
              "type": "checkbox",
              "label": "Services:",
              "placeholder": "",
              "required": false,
              "halfWidth": false,
              "options": [
                "Obstetric Services",
                "Gynecology Services",
                "Aesthetics Services",
                "Other"
              ]
            },
            {
              "type": "radio",
              "label": "Location",
              "placeholder": "",
              "required": true,
              "halfWidth": false,
              "options": [
                "Ringgold",
                "Ooltewah"
              ]
            },
            {
              "type": "textarea",
              "label": "Message (optional)",
              "placeholder": "Have any questions or feedback?",
              "required": false,
              "halfWidth": false,
              "options": []
            }
          ]
        }
      ]
    }
  ],
  "aboutSections": [],
  "homeSections": [
    {
      "type": "team",
      "label": "",
      "background": "alt",
      "anchorId": "our-physicians",
      "heading": "Our Physicians",
      "items": []
    },
    {
      "type": "button",
      "label": "",
      "background": "light",
      "anchorId": "button",
      "primary_linkType": "none",
      "primary_linkLabel": "",
      "primary_linkUrl": "about",
      "primary_anchorId": "",
      "secondary_linkType": "internal",
      "secondary_linkLabel": "Learn More About Us",
      "secondary_linkUrl": "about",
      "secondary_anchorId": ""
    },
    {
      "type": "bullets",
      "label": "",
      "background": "alt",
      "anchorId": "bullets",
      "heading": "Our Locations",
      "subtitle": "",
      "items": [
        {
          "icon": "GA",
          "title": "Ringgold Office",
          "desc": "93 Robin Rd.\nRinggold, GA",
          "linkType": "none",
          "linkUrl": "home",
          "anchorId": ""
        },
        {
          "icon": "TN",
          "title": "Ooltewah Office",
          "desc": "",
          "linkType": "none",
          "linkUrl": "home",
          "anchorId": ""
        }
      ]
    }
  ],
  "footerBio": "",
  "animateStats": false,
  "contactSubmitLabel": "Submit",
  "contactSuccessMsg": "",
  "search": {
    "placeholder": "Search...",
    "noResultsMessage": "No results for '{query}'",
    "noResultsSubtext": "Try a different search term.",
    "resultsPerPage": 5,
    "excludedPages": []
  },
  "siteAccess": "public",
  "sessionDays": 7,
  "pinPad": {
    "headline": "Members Only",
    "subtext": "Restricted Access",
    "wrongMsg": "Incorrect PIN. Try again.",
    "theme": "dark",
    "lockEmoji": "🔒",
    "backLabel": "← Back to Home",
    "maxAttempts": 3,
    "welcomeMsg": "Welcome back, {name}",
    "commissionerMsg": "Commissioner Access Granted",
    "welcomeDuration": 2,
    "showImposter": true,
    "imposterHeadline": "ACCESS DENIED",
    "imposterMsg": "This attempt has been logged.",
    "imposterDuration": 3
  },
  "members": [],
  "pageAccess": {
    "home": "public",
    "about": "public",
    "cp-0": "public",
    "cp-1": "public",
    "cp-2": "public"
  },
  "_savedAt": 1777614871216
};
